//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Net.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class asp_projectEntities : DbContext
    {
        public asp_projectEntities()
            : base("name=asp_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        /*public virtual DbSet<activite> activite { get; set; }*/
        public virtual DbSet<admin> admin { get; set; }
        /*public virtual DbSet<association> association { get; set; }
        public virtual DbSet<BDE> BDE { get; set; }
        public virtual DbSet<club> club { get; set; }
        public virtual DbSet<filiere> filiere { get; set; }
        public virtual DbSet<gallerie> gallerie { get; set; }
        public virtual DbSet<laureat> laureat { get; set; }
        public virtual DbSet<membre_BDE> membre_BDE { get; set; }
        public virtual DbSet<Responsable> Responsable { get; set; }*/
    }
}
